In [1]:
import importlib
import pandas
import utils
import data.loader
importlib.reload(utils)
importlib.reload(data.loader)
from data.loader import InsilicoDataLoader

### GET_EXPERIMENTAL_SYNERGIES

In [13]:
synergies_exp_processed = utils.load_dataframe(folder="tests\\data", pattern="synergies_observed_bliss.csv")
# Clean cell line column (uppercase and replace underscore with nothing)
synergies_exp_processed['cell_line'] = synergies_exp_processed['cell_line'].str.upper().str.replace('_', '')
synergies_exp_processed.columns

Index(['drug1', 'drug2', 'cell_line', 'synergy', 'drug1_ID', 'drug2_ID'], dtype='object')

In [14]:
import importlib
import features.synergy_observations
importlib.reload(features.synergy_observations)
from features.synergy_observations import get_experimental_cell_synergies

cell_lines = ['C2BBE1', 'CAR1']
synergies_exp_df = synergies_exp_processed
output_dir = "tests\\BooLEVARD\\BL_results"
anchorID = "drug1_ID"
libraryID = "drug2_ID"

for cell_line in cell_lines:
    get_experimental_cell_synergies(
        cell_line=cell_line,
        synergies_exp_df=synergies_exp_df,
        output_directory=output_dir,
        anchorID=anchorID,
        libraryID=libraryID,
        synergy_values=True 
    )

Observed synergies file created for C2BBE1 in output directory

Observed synergies file created for CAR1 in output directory

### GET_ANALYSIS_FOLDER

In [ ]:
import importlib
import utils
import data.loader
importlib.reload(utils)
importlib.reload(data.loader)
from data.loader import DataLoader

print("=== Testing DrugLogics Pipeline ===")
base_path = "tests\\DrugLogics\\20250107"
cell_info_path = None
run_results_path = base_path + '\\drabme_out'
analysis_folder = "test2"
cell_lines = ['C2BBe1', 'CaR-1']
run_date = '20250804'

test_DrugLogics = DataLoader(
    base_path=base_path,
    cell_info_path=base_path,
    cell_lines=cell_lines,
    pipeline='DrugLogics',
    experimental_observations=True,
    run_results_path=run_results_path,
    analysis_folder=analysis_folder,
    run_date=run_date,
    verbose=True 
)

test_DrugLogics.make_analysis_folders()

=== Testing DrugLogics Pipeline ===

Main analysis folder created at: tests\DrugLogics\20250107\run_analysis\test2
Copied ['*ensemblewise_synergies*', '*observed_synergies*'] to tests\DrugLogics\20250107\run_analysis\test2\C2BBe1
Copied ['*ensemblewise_synergies*', '*observed_synergies*'] to tests\DrugLogics\20250107\run_analysis\test2\C2BBe1
Total files copied: 2
Copied ['*ensemblewise_synergies*', '*observed_synergies*'] to tests\DrugLogics\20250107\run_analysis\test2\CaR-1
Copied ['*ensemblewise_synergies*', '*observed_synergies*'] to tests\DrugLogics\20250107\run_analysis\test2\CaR-1
Total files copied: 2

Total folders created: 2
Folders with no files copied: 0

In [ ]:
# Test with corrected BooLEVARD logic
import importlib
import utils
import data.loader
importlib.reload(utils)
importlib.reload(data.loader)
from data.loader import DataLoader

# TEST with BooLEVARD pipeline with corrected cell line matching:
print("=== Testing BooLEVARD Pipeline ===")
base_path = "tests\\BooLEVARD"
cell_info_path = "tests\\BooLEVARD\\BL_results"
run_results_path = base_path + '\\BL_results'
analysis_folder = "test2"
cell_lines = None
run_date = None

test_BooLEVARD = DataLoader(
    base_path=base_path,
    cell_info_path=cell_info_path,
    cell_lines=cell_lines,
    pipeline='BooLEVARD',
    experimental_observations=True,
    run_results_path=run_results_path,
    analysis_folder=analysis_folder,
    run_date=run_date,
    verbose=True 
)

test_BooLEVARD.make_analysis_folders()

=== Testing BooLEVARD Pipeline ===

Discovered cell lines from tests\BooLEVARD\BL_results
Cell lines: ['C2BBE1', 'CAR1']
Warning: Could not reset existing folder due to permissions. Using existing folder: tests\BooLEVARD\run_analysis\test2

Main analysis folder created at: tests\BooLEVARD\run_analysis\test2
Warning: Could not reset existing folder due to permissions. Using existing folder: tests\BooLEVARD\run_analysis\test2\C2BBE1
Copied ['SynergyExcess_C2BBE1.tsv', '*observed_synergies*'] to tests\BooLEVARD\run_analysis\test2\C2BBE1
Copied ['SynergyExcess_C2BBE1.tsv', '*observed_synergies*'] to tests\BooLEVARD\run_analysis\test2\C2BBE1
Total files copied: 2
Warning: Could not reset existing folder due to permissions. Using existing folder: tests\BooLEVARD\run_analysis\test2\CAR1
Copied ['SynergyExcess_CAR1.tsv', '*observed_synergies*'] to tests\BooLEVARD\run_analysis\test2\CAR1
Copied ['SynergyExcess_CAR1.tsv', '*observed_synergies*'] to tests\BooLEVARD\run_analysis\test2\CAR1
Total files copied: 2

Total folders created: 2
Folders with no files copied: 0

### FETCH_SYNERGY_DATA

In [4]:
run_results_DL_dict = test_DrugLogics.fetch_synergy_data(experimental_observations=True)
run_results_DL_dict

{'C2BBe1': (   Perturbation anchor_ID library_ID    synergy
  0   PD_01-PD_03     PD_01      PD_03   2.639919
  1   PD_03-PD_04     PD_03      PD_04   0.949744
  2   PD_03-PD_09     PD_03      PD_09  -2.258419
  3   PD_03-PD_10     PD_03      PD_10   1.937047
  4   PD_03-PD_08     PD_03      PD_08  -0.135083
  5   PD_03-PD_11     PD_03      PD_11   4.525286
  6   PD_01-PD_04     PD_01      PD_04  12.319194
  7   PD_02-PD_06     PD_02      PD_06  -8.414304
  8   PD_02-PD_05     PD_02      PD_05 -10.470380
  9   PD_02-PD_08     PD_02      PD_08  -4.380535
  10  PD_02-PD_07     PD_02      PD_07  -3.477348,
     Perturbation    C2BBe1
  0   PD_03-PD_08 -0.131169
  1   PD_02-PD_07 -0.015741
  2   PD_02-PD_08  0.000000
  3   PD_01-PD_04 -0.515595
  4   PD_02-PD_06 -0.004193
  5   PD_02-PD_05  0.000000
  6   PD_01-PD_03 -0.042285
  7   PD_03-PD_10 -0.150338
  8   PD_03-PD_09 -0.118963
  9   PD_03-PD_04 -0.174183
  10  PD_03-PD_11 -0.223805),
 'CaR-1': (   Perturbation anchor_ID library_ID    synergy
  0   PD_01-PD_03     PD_01      PD_03  -3.978478
  1   PD_03-PD_04     PD_03      PD_04   2.803685
  2   PD_03-PD_09     PD_03      PD_09   8.998710
  3   PD_03-PD_10     PD_03      PD_10  -7.804146
  4   PD_03-PD_08     PD_03      PD_08   2.642531
  5   PD_03-PD_11     PD_03      PD_11   3.763021
  6   PD_01-PD_04     PD_01      PD_04   7.888638
  7   PD_02-PD_06     PD_02      PD_06  27.133862
  8   PD_02-PD_05     PD_02      PD_05  10.599924
  9   PD_02-PD_08     PD_02      PD_08  -5.983096
  10  PD_02-PD_07     PD_02      PD_07  15.984258,
     Perturbation     CaR-1
  0   PD_03-PD_08 -0.114319
  1   PD_02-PD_07 -0.027944
  2   PD_02-PD_08 -0.014875
  3   PD_01-PD_04 -0.624607
  4   PD_02-PD_06 -0.011111
  5   PD_02-PD_05  0.000000
  6   PD_01-PD_03 -0.001191
  7   PD_03-PD_10 -0.101476
  8   PD_03-PD_09 -0.051361
  9   PD_03-PD_04 -0.360992
  10  PD_03-PD_11 -0.178289)}

In [5]:
run_results_BL_dict = test_BooLEVARD.fetch_synergy_data(experimental_observations=True)
run_results_BL_dict

{'C2BBE1': (   Perturbation anchor_ID library_ID    synergy
  0   PD_01-PD_03     PD_01      PD_03   2.639919
  1   PD_03-PD_04     PD_03      PD_04   0.949744
  2   PD_03-PD_09     PD_03      PD_09  -2.258419
  3   PD_03-PD_10     PD_03      PD_10   1.937047
  4   PD_03-PD_08     PD_03      PD_08  -0.135083
  5   PD_03-PD_11     PD_03      PD_11   4.525286
  6   PD_01-PD_04     PD_01      PD_04  12.319194
  7   PD_02-PD_06     PD_02      PD_06  -8.414304
  8   PD_02-PD_05     PD_02      PD_05 -10.470380
  9   PD_02-PD_08     PD_02      PD_08  -4.380535
  10  PD_02-PD_07     PD_02      PD_07  -3.477348,
     Perturbation    C2BBE1
  0   PD_01-PD_02  0.065052
  1   PD_01-PD_03  0.118641
  2   PD_01-PD_07  0.080314
  3   PD_01-PD_08  0.065541
  4   PD_03-PD_05 -0.373627
  5   PD_03-PD_06  0.014713
  6   PD_03-PD_07  0.113875
  7   PD_03-PD_08  0.114937
  8   PD_03-PD_09  0.037713
  9   PD_03-PD_10 -0.017232
  10  PD_05-PD_07  0.148097
  11  PD_05-PD_08 -0.082051
  12  PD_05-PD_12  0.057233
  13  PD_06-PD_07  0.008812
  14  PD_06-PD_08  0.013676
  15  PD_07-PD_08 -0.008252
  16  PD_07-PD_10 -0.047804
  17  PD_07-PD_12 -0.042015
  18  PD_08-PD_10 -0.032108
  19  PD_08-PD_11  0.199286),
 'CAR1': (   Perturbation anchor_ID library_ID    synergy
  0   PD_01-PD_03     PD_01      PD_03  -3.978478
  1   PD_03-PD_04     PD_03      PD_04   2.803685
  2   PD_03-PD_09     PD_03      PD_09   8.998710
  3   PD_03-PD_10     PD_03      PD_10  -7.804146
  4   PD_03-PD_08     PD_03      PD_08   2.642531
  5   PD_03-PD_11     PD_03      PD_11   3.763021
  6   PD_01-PD_04     PD_01      PD_04   7.888638
  7   PD_02-PD_06     PD_02      PD_06  27.133862
  8   PD_02-PD_05     PD_02      PD_05  10.599924
  9   PD_02-PD_08     PD_02      PD_08  -5.983096
  10  PD_02-PD_07     PD_02      PD_07  15.984258,
     Perturbation      CAR1
  0   PD_01-PD_02  0.065052
  1   PD_01-PD_03  0.118641
  2   PD_01-PD_07  0.080314
  3   PD_01-PD_08  0.065541
  4   PD_03-PD_05 -0.373627
  5   PD_03-PD_06  0.014713
  6   PD_03-PD_07  0.113875
  7   PD_03-PD_08  0.114937
  8   PD_03-PD_09  0.037713
  9   PD_03-PD_10 -0.017232
  10  PD_05-PD_07  0.148097
  11  PD_05-PD_08 -0.082051
  12  PD_05-PD_12  0.057233
  13  PD_06-PD_07  0.008812
  14  PD_06-PD_08  0.013676
  15  PD_07-PD_08 -0.008252
  16  PD_07-PD_10 -0.047804
  17  PD_07-PD_12 -0.042015
  18  PD_08-PD_10 -0.032108
  19  PD_08-PD_11  0.199286)}

### DRUG PROFILES DICT

In [38]:
importlib.reload(data.drug_profiles)
from data.drug_profiles import get_drugprofiles

input_path = "tests\\data"
output_path = "tests\\output\\"

drug_profiles = get_drugprofiles(input_path,)

PD_inhibitors_dict, Drugnames_PD_dict, PD_drugnames_dict, inhibitorgroups_dict, Drugnames_inhibitor_dict, PD_targets_dict = drug_profiles.values()

PD_inhibitors_dict

{'PD_01': 'AKT_inhibitors',
 'PD_02': 'CHK1_inhibitors',
 'PD_03': 'mTOR_inhibitors',
 'PD_04': 'EGFR_inhibitors',
 'PD_05': 'PARP_inhibitors',
 'PD_06': 'Wee1_inhibitors',
 'PD_07': 'MK2_inhibitors',
 'PD_08': 'CyclinD_inhibitors',
 'PD_09': 'BCL2L1_inhibitors',
 'PD_10': 'BCL2_inhibitors',
 'PD_11': 'ERK_inhibitors'}

### SYNERGY_PREDICTIONS

In [6]:
mapping = utils.load_dataframe(folder="tests\\data", pattern="drug_profiles.csv")
map_names_dict = mapping.groupby('PD_profile')['drug_name'].apply(list).to_dict()
map_target_dict = mapping.drop_duplicates(subset=['node_targets', 'PD_profile'])
map_target_dict = map_target_dict.set_index('PD_profile')['node_targets'].to_dict()
map_names_dict

{'PD_01': ['Ipatasertib', 'Capivasertib'],
 'PD_02': ['PF 477736', 'Prexasertib'],
 'PD_03': ['AZD-8055', 'Everolimus', 'Torin 1'],
 'PD_04': ['Lapatinib', 'Neratinib'],
 'PD_05': ['Niraparib', 'Olaparib'],
 'PD_06': ['MK-1775 (Advosertib)'],
 'PD_07': ['PF-3644022'],
 'PD_08': ['Palbociclib'],
 'PD_09': ['Navitoclax'],
 'PD_10': ['Obatoclax Mesylate'],
 'PD_11': ['Ulixertinib', 'Ulixertinib', 'Ulixertinib']}

In [26]:
import importlib
import features.synergy_predictions
importlib.reload(features.synergy_predictions)
from features.synergy_predictions import get_synergy_predictions

# TEST with DrugLogics pipeline:
synergy_results_dict = run_results_DL_dict
combination_type = 'drugnames'
mapping_names_dict = map_names_dict
mapping_target_dict = map_target_dict
drugID = 'drug_name'
targetID = 'node_targets'
synergy_results = get_synergy_predictions(
    synergy_results_dict=synergy_results_dict,
    combination_type=combination_type,
    mapping_names_dict=mapping_names_dict,
    mapping_target_dict=mapping_target_dict,
    drugID_type=drugID,
    target_type=targetID,
    remove_duplicates=False,
    add_experimental_observations=True,
)

Data saved to tests\synergy_predictions.csv as CSV.

In [8]:
synergy_results

,Perturbation,C2BBe1,CaR-1,PD_A,PD_B,drug_name_A,drug_name_B,node_targets_A,node_targets_B,drug_combination,Experimental_C2BBe1,Experimental_CaR-1
0,PD_01-PD_03,-0.042285,-0.001191,PD_01,PD_03,"Ipatasertib, Capivasertib","AZD-8055, Everolimus, Torin 1",['AKT1'],"['mTOR_c2', 'mTOR_c1']","(Ipatasertib, Capivasertib) + (AZD-8055, Evero...",2.639919,-3.978478
1,PD_01-PD_04,-0.515595,-0.624607,PD_01,PD_04,"Ipatasertib, Capivasertib","Lapatinib, Neratinib",['AKT1'],"['ERBB2', 'EGFR']","(Ipatasertib, Capivasertib) + (Lapatinib, Nera...",12.319194,7.888638
2,PD_02-PD_05,0.000000,0.000000,PD_02,PD_05,"PF 477736, Prexasertib","Niraparib, Olaparib","['CHEK1', 'CHEK2']",['PARP1'],"(PF 477736, Prexasertib) + (Niraparib, Olaparib)",-10.470380,10.599924
3,PD_02-PD_06,-0.004193,-0.011111,PD_02,PD_06,"PF 477736, Prexasertib",MK-1775 (Advosertib),"['CHEK1', 'CHEK2']","['WEE1', 'PLK1']","(PF 477736, Prexasertib) + (MK-1775 (Advosertib))",-8.414304,27.133862
4,PD_02-PD_07,-0.015741,-0.027944,PD_02,PD_07,"PF 477736, Prexasertib",PF-3644022,"['CHEK1', 'CHEK2']",['MAPKAPK2'],"(PF 477736, Prexasertib) + (PF-3644022)",-3.477348,15.984258
5,PD_02-PD_08,0.000000,-0.014875,PD_02,PD_08,"PF 477736, Prexasertib",Palbociclib,"['CHEK1', 'CHEK2']","['CCND1', 'CyclinD_CDK4_6', 'CyclinE_CDK2']","(PF 477736, Prexasertib) + (Palbociclib)",-4.380535,-5.983096
6,PD_03-PD_04,-0.174183,-0.360992,PD_03,PD_04,"AZD-8055, Everolimus, Torin 1","Lapatinib, Neratinib","['mTOR_c2', 'mTOR_c1']","['ERBB2', 'EGFR']","(AZD-8055, Everolimus, Torin 1) + (Lapatinib, ...",0.949744,2.803685
7,PD_03-PD_08,-0.131169,-0.114319,PD_03,PD_08,"AZD-8055, Everolimus, Torin 1",Palbociclib,"['mTOR_c2', 'mTOR_c1']","['CCND1', 'CyclinD_CDK4_6', 'CyclinE_CDK2']","(AZD-8055, Everolimus, Torin 1) + (Palbociclib)",-0.135083,2.642531
8,PD_03-PD_09,-0.118963,-0.051361,PD_03,PD_09,"AZD-8055, Everolimus, Torin 1",Navitoclax,"['mTOR_c2', 'mTOR_c1']","['BCL2L1', 'BCL2']","(AZD-8055, Everolimus, Torin 1) + (Navitoclax)",-2.258419,8.998710
9,PD_03-PD_10,-0.150338,-0.101476,PD_03,PD_10,"AZD-8055, Everolimus, Torin 1",Obatoclax Mesylate,"['mTOR_c2', 'mTOR_c1']",['BCL2'],"(AZD-8055, Everolimus, Torin 1) + (Obatoclax M...",1.937047,-7.804146
10,PD_03-PD_11,-0.223805,-0.178289,PD_03,PD_11,"AZD-8055, Everolimus, Torin 1","Ulixertinib, Ulixertinib, Ulixertinib","['mTOR_c2', 'mTOR_c1']",['ERK_f'],"(AZD-8055, Everolimus, Torin 1) + (Ulixertinib...",4.525286,3.763021

In [ ]:
import importlib
import features.synergy_predictions
importlib.reload(features.synergy_predictions)
from features.synergy_predictions import get_synergy_predictions

# TEST with BooLEVARD
synergy_results_dict = run_results_BL_dict
combination_type = 'drugnames'
mapping_names_dict = map_names_dict
mapping_target_dict = map_target_dict
drugID = 'drug_name'
targetID = 'node_targets'
synergy_results = get_synergy_predictions(
    synergy_results_dict=synergy_results_dict,
    combination_type=combination_type,
    mapping_names_dict=mapping_names_dict,
    mapping_target_dict=mapping_target_dict,
    drugID_type=drugID,
    target_type=targetID,
    remove_duplicates=False,
    add_experimental_observations=True,
)

In [10]:
synergy_results

,Perturbation,C2BBE1,CAR1,PD_A,PD_B,drug_name_A,drug_name_B,node_targets_A,node_targets_B,drug_combination,Experimental_C2BBE1,Experimental_CAR1
0,PD_01-PD_02,0.065052,0.065052,PD_01,PD_02,"Ipatasertib, Capivasertib","PF 477736, Prexasertib",['AKT1'],"['CHEK1', 'CHEK2']","(Ipatasertib, Capivasertib) + (PF 477736, Prex...",NaN,NaN
1,PD_01-PD_03,0.118641,0.118641,PD_01,PD_03,"Ipatasertib, Capivasertib","AZD-8055, Everolimus, Torin 1",['AKT1'],"['mTOR_c2', 'mTOR_c1']","(Ipatasertib, Capivasertib) + (AZD-8055, Evero...",2.639919,-3.978478
2,PD_01-PD_07,0.080314,0.080314,PD_01,PD_07,"Ipatasertib, Capivasertib",PF-3644022,['AKT1'],['MAPKAPK2'],"(Ipatasertib, Capivasertib) + (PF-3644022)",NaN,NaN
3,PD_01-PD_08,0.065541,0.065541,PD_01,PD_08,"Ipatasertib, Capivasertib",Palbociclib,['AKT1'],"['CCND1', 'CyclinD_CDK4_6', 'CyclinE_CDK2']","(Ipatasertib, Capivasertib) + (Palbociclib)",NaN,NaN
4,PD_03-PD_05,-0.373627,-0.373627,PD_03,PD_05,"AZD-8055, Everolimus, Torin 1","Niraparib, Olaparib","['mTOR_c2', 'mTOR_c1']",['PARP1'],"(AZD-8055, Everolimus, Torin 1) + (Niraparib, ...",NaN,NaN
5,PD_03-PD_06,0.014713,0.014713,PD_03,PD_06,"AZD-8055, Everolimus, Torin 1",MK-1775 (Advosertib),"['mTOR_c2', 'mTOR_c1']","['WEE1', 'PLK1']","(AZD-8055, Everolimus, Torin 1) + (MK-1775 (Ad...",NaN,NaN
6,PD_03-PD_07,0.113875,0.113875,PD_03,PD_07,"AZD-8055, Everolimus, Torin 1",PF-3644022,"['mTOR_c2', 'mTOR_c1']",['MAPKAPK2'],"(AZD-8055, Everolimus, Torin 1) + (PF-3644022)",NaN,NaN
7,PD_03-PD_08,0.114937,0.114937,PD_03,PD_08,"AZD-8055, Everolimus, Torin 1",Palbociclib,"['mTOR_c2', 'mTOR_c1']","['CCND1', 'CyclinD_CDK4_6', 'CyclinE_CDK2']","(AZD-8055, Everolimus, Torin 1) + (Palbociclib)",-0.135083,2.642531
8,PD_03-PD_09,0.037713,0.037713,PD_03,PD_09,"AZD-8055, Everolimus, Torin 1",Navitoclax,"['mTOR_c2', 'mTOR_c1']","['BCL2L1', 'BCL2']","(AZD-8055, Everolimus, Torin 1) + (Navitoclax)",-2.258419,8.998710
9,PD_03-PD_10,-0.017232,-0.017232,PD_03,PD_10,"AZD-8055, Everolimus, Torin 1",Obatoclax Mesylate,"['mTOR_c2', 'mTOR_c1']",['BCL2'],"(AZD-8055, Everolimus, Torin 1) + (Obatoclax M...",1.937047,-7.804146
10,PD_05-PD_07,0.148097,0.148097,PD_05,PD_07,"Niraparib, Olaparib",PF-3644022,['PARP1'],['MAPKAPK2'],"(Niraparib, Olaparib) + (PF-3644022)",NaN,NaN
11,PD_05-PD_08,-0.082051,-0.082051,PD_05,PD_08,"Niraparib, Olaparib",Palbociclib,['PARP1'],"['CCND1', 'CyclinD_CDK4_6', 'CyclinE_CDK2']","(Niraparib, Olaparib) + (Palbociclib)",NaN,NaN
12,PD_05-PD_12,0.057233,0.057233,PD_05,PD_12,"Niraparib, Olaparib",nan,['PARP1'],NaN,"(Niraparib, Olaparib) + (nan)",NaN,NaN
13,PD_06-PD_07,0.008812,0.008812,PD_06,PD_07,MK-1775 (Advosertib),PF-3644022,"['WEE1', 'PLK1']",['MAPKAPK2'],(MK-1775 (Advosertib)) + (PF-3644022),NaN,NaN
14,PD_06-PD_08,0.013676,0.013676,PD_06,PD_08,MK-1775 (Advosertib),Palbociclib,"['WEE1', 'PLK1']","['CCND1', 'CyclinD_CDK4_6', 'CyclinE_CDK2']",(MK-1775 (Advosertib)) + (Palbociclib),NaN,NaN
15,PD_07-PD_08,-0.008252,-0.008252,PD_07,PD_08,PF-3644022,Palbociclib,['MAPKAPK2'],"['CCND1', 'CyclinD_CDK4_6', 'CyclinE_CDK2']",(PF-3644022) + (Palbociclib),NaN,NaN
16,PD_07-PD_10,-0.047804,-0.047804,PD_07,PD_10,PF-3644022,Obatoclax Mesylate,['MAPKAPK2'],['BCL2'],(PF-3644022) + (Obatoclax Mesylate),NaN,NaN
17,PD_07-PD_12,-0.042015,-0.042015,PD_07,PD_12,PF-3644022,nan,['MAPKAPK2'],NaN,(PF-3644022) + (nan),NaN,NaN
18,PD_08-PD_10,-0.032108,-0.032108,PD_08,PD_10,Palbociclib,Obatoclax Mesylate,"['CCND1', 'CyclinD_CDK4_6', 'CyclinE_CDK2']",['BCL2'],(Palbociclib) + (Obatoclax Mesylate),NaN,NaN
19,PD_08-PD_11,0.199286,0.199286,PD_08,PD_11,Palbociclib,"Ulixertinib, Ulixertinib, Ulixertinib","['CCND1', 'CyclinD_CDK4_6', 'CyclinE_CDK2']",['ERK_f'],"(Palbociclib) + (Ulixertinib, Ulixertinib, Uli...",NaN,NaN

### CONVERGE SYNERGIES

In [ ]:
# Test the new normalization function
import importlib
import sys
if 'synco.features.compare' in sys.modules:
    importlib.reload(sys.modules['synco.features.compare'])

from synco.features.compare import _normalize_inhibitor_combination, _normalize_combinations_in_df

# Test normalization function
test_combinations = [
    "AKT_inhibitors + mTOR_inhibitors",
    "mTOR_inhibitors + AKT_inhibitors",
    "CHK1_inhibitors + PARP_inhibitors",
    "PARP_inhibitors + CHK1_inhibitors",
    "Single_inhibitor"  # Test single inhibitor (should remain unchanged)
]

print("Testing normalization:")
for combo in test_combinations:
    normalized = _normalize_inhibitor_combination(combo)
    print(f"'{combo}' -> '{normalized}'")

# Test with DataFrame
import pandas as pd
test_df = pd.DataFrame({
    'inhibitor_combination': test_combinations,
    'synergy': [0.1, 0.2, 0.3, 0.4, 0.5]
})

print("\nOriginal DataFrame:")
print(test_df)

normalized_df = _normalize_combinations_in_df(test_df)
print("\nNormalized DataFrame:")
print(normalized_df)

In [27]:
import features.converge_synergies
importlib.reload(features.converge_synergies)

anchorID = 'drug1_ID'
libraryID = 'drug2_ID'
anchor_name = 'drug1'
library_name = 'drug2'
inhibitor_groups = PD_inhibitors_dict
targets_dict = PD_targets_dict

converge_experimental = features.converge_synergies.converge_synergies(
    df=synergies_exp_processed,
    anchorID=anchorID,
    libraryID=libraryID,
    anchor_name=anchor_name,
    library_name=library_name,
    inhibitor_groups=inhibitor_groups,
    targets_dict=targets_dict,
)

Data saved to tests\full_df.csv as CSV.
Data saved to tests\drug_names_synergies_df.csv as CSV.
Data saved to tests\inhibitor_group_synergies_df.csv as CSV.

In [16]:
exp_full_df, exp_drug_names_synergies_df, exp_inhibitor_group_synergies_df = converge_experimental
exp_inhibitor_group_synergies_df

                    inhibitor_combination cell_line    synergy
0        AKT_inhibitors + EGFR_inhibitors    C2BBE1   8.710664
1    CHK1_inhibitors + CyclinD_inhibitors    C2BBE1  -6.760625
2        CHK1_inhibitors + MK2_inhibitors    C2BBE1  -4.206320
3       CHK1_inhibitors + PARP_inhibitors    C2BBE1 -12.782885
4       CHK1_inhibitors + Wee1_inhibitors    C2BBE1  -1.938123
..                                    ...       ...        ...
171   mTOR_inhibitors + BCL2L1_inhibitors       T84  29.283150
172     mTOR_inhibitors + BCL2_inhibitors       T84  27.151116
173  mTOR_inhibitors + CyclinD_inhibitors       T84  39.014561
174     mTOR_inhibitors + EGFR_inhibitors       T84  23.171955
175      mTOR_inhibitors + ERK_inhibitors       T84  45.823523

[176 rows x 3 columns]

In [17]:
importlib.reload(features.converge_synergies)

anchorID = 'PD_A'
libraryID = 'PD_B'
anchor_name = 'drug_name_A'
library_name = 'drug_name_B'
cell_line_list = ['C2BBE1', 'CAR1']

converge_predictions = features.converge_synergies.converge_synergies(
    df=synergy_results,
    anchorID=anchorID,
    libraryID=libraryID,
    inhibitor_groups=inhibitor_groups,
    targets_dict=targets_dict,
    cell_line_list=cell_line_list,
    predicted=True,
)

In [18]:
pred_full_df, pred_drug_names_synergies_df, pred_inhibitor_group_synergies_df = converge_predictions
pred_inhibitor_group_synergies_df

                   inhibitor_combination cell_line   synergy
0       AKT_inhibitors + CHK1_inhibitors    C2BBE1 -0.065052
1       AKT_inhibitors + mTOR_inhibitors    C2BBE1 -0.118641
2        AKT_inhibitors + MK2_inhibitors    C2BBE1 -0.080314
3    AKT_inhibitors + CyclinD_inhibitors    C2BBE1 -0.065541
4      mTOR_inhibitors + PARP_inhibitors    C2BBE1  0.373627
5      mTOR_inhibitors + Wee1_inhibitors    C2BBE1 -0.014713
6       mTOR_inhibitors + MK2_inhibitors    C2BBE1 -0.113875
7   mTOR_inhibitors + CyclinD_inhibitors    C2BBE1 -0.114937
8    mTOR_inhibitors + BCL2L1_inhibitors    C2BBE1 -0.037713
9      mTOR_inhibitors + BCL2_inhibitors    C2BBE1  0.017232
10      PARP_inhibitors + MK2_inhibitors    C2BBE1 -0.148097
11  PARP_inhibitors + CyclinD_inhibitors    C2BBE1  0.082051
12      Wee1_inhibitors + MK2_inhibitors    C2BBE1 -0.008812
13  Wee1_inhibitors + CyclinD_inhibitors    C2BBE1 -0.013676
14   MK2_inhibitors + CyclinD_inhibitors    C2BBE1  0.008252
15      MK2_inhibitors + BCL2_inhibitors    C2BBE1  0.047804
16  CyclinD_inhibitors + BCL2_inhibitors    C2BBE1  0.032108
17   CyclinD_inhibitors + ERK_inhibitors    C2BBE1 -0.199286
18      AKT_inhibitors + CHK1_inhibitors      CAR1 -0.065052
19      AKT_inhibitors + mTOR_inhibitors      CAR1 -0.118641
20       AKT_inhibitors + MK2_inhibitors      CAR1 -0.080314
21   AKT_inhibitors + CyclinD_inhibitors      CAR1 -0.065541
22     mTOR_inhibitors + PARP_inhibitors      CAR1  0.373627
23     mTOR_inhibitors + Wee1_inhibitors      CAR1 -0.014713
24      mTOR_inhibitors + MK2_inhibitors      CAR1 -0.113875
25  mTOR_inhibitors + CyclinD_inhibitors      CAR1 -0.114937
26   mTOR_inhibitors + BCL2L1_inhibitors      CAR1 -0.037713
27     mTOR_inhibitors + BCL2_inhibitors      CAR1  0.017232
28      PARP_inhibitors + MK2_inhibitors      CAR1 -0.148097
29  PARP_inhibitors + CyclinD_inhibitors      CAR1  0.082051
30      Wee1_inhibitors + MK2_inhibitors      CAR1 -0.008812
31  Wee1_inhibitors + CyclinD_inhibitors      CAR1 -0.013676
32   MK2_inhibitors + CyclinD_inhibitors      CAR1  0.008252
33      MK2_inhibitors + BCL2_inhibitors      CAR1  0.047804
34  CyclinD_inhibitors + BCL2_inhibitors      CAR1  0.032108
35   CyclinD_inhibitors + ERK_inhibitors      CAR1 -0.199286

### COMPARE SYNERGIES

In [ ]:
# Manual adjustment is no longer needed - compare.py now handles bidirectional combinations automatically
print("Automatic normalization is now integrated into compare_synergies function")
print("No manual adjustment of inhibitor combinations required!")

In [ ]:
# Test the updated compare_synergies function with automatic normalization
import importlib
import sys
if 'synco.features.compare' in sys.modules:
    importlib.reload(sys.modules['synco.features.compare'])

from synco.features.compare import compare_synergies

# No need to manually adjust combinations anymore - the function should handle it automatically
print("Experimental combinations:")
print(exp_inhibitor_group_synergies_df['inhibitor_combination'].unique())
print("\nPrediction combinations:")  
print(pred_inhibitor_group_synergies_df['inhibitor_combination'].unique())

# Run comparison with automatic normalization
compared_synergies_df, skipped_info = compare_synergies(
    df_experiment=exp_inhibitor_group_synergies_df,
    df_prediction=pred_inhibitor_group_synergies_df,
    cell_line_list=['C2BBE1', 'CAR1'],
    threshold=0.0,
    analysis_mode='inhibitor_combination',
    output_path='tests\\compared_synergies.csv'
)

=== COMPARISON SUMMARY ===

Items in experimental data: 11
Items in predicted data: 18
Common items to compare: 4
Skipped from experimental: 7
Skipped from predicted: 14
Experimental-only inhibitor_combinations: ['AKT_inhibitors + EGFR_inhibitors', 'CHK1_inhibitors + CyclinD_inhibitors', 'CHK1_inhibitors + MK2_inhibitors', 'CHK1_inhibitors + PARP_inhibitors', 'CHK1_inhibitors + Wee1_inhibitors', 'mTOR_inhibitors + EGFR_inhibitors', 'mTOR_inhibitors + ERK_inhibitors']
Predicted-only inhibitor_combinations: ['AKT_inhibitors + CHK1_inhibitors', 'AKT_inhibitors + CyclinD_inhibitors', 'AKT_inhibitors + MK2_inhibitors', 'CyclinD_inhibitors + BCL2_inhibitors', 'CyclinD_inhibitors + ERK_inhibitors', 'MK2_inhibitors + BCL2_inhibitors', 'MK2_inhibitors + CyclinD_inhibitors', 'PARP_inhibitors + CyclinD_inhibitors', 'PARP_inhibitors + MK2_inhibitors', 'Wee1_inhibitors + CyclinD_inhibitors', 'Wee1_inhibitors + MK2_inhibitors', 'mTOR_inhibitors + MK2_inhibitors', 'mTOR_inhibitors + PARP_inhibitors', 'mTOR_inhibitors + Wee1_inhibitors']

=== GLOBAL RESULTS ===

Total comparisons: 8
Global matches: 3 (37.50%)
Global mismatches: 5 (62.50%)
Global True Positives: 1
Global True Negatives: 2
Global False Positives: 1
Global False Negatives: 4
Global Accuracy: 37.50%
Global Recall: 20.00%
Global Precision: 50.00%
Data saved to tests\compared_synergies.csv as CSV.

In [61]:
compared_synergies_df

,True Positive,True Negative,False Positive,False Negative,Total,Match,Mismatch,Match %,Mismatch %,Accuracy,Recall,Precision
mTOR_inhibitors + AKT_inhibitors,0,1,0,1,2,1,1,50.0,50.0,50.0,0.0,0.0
mTOR_inhibitors + BCL2_inhibitors,1,0,1,0,2,1,1,50.0,50.0,50.0,100.0,50.0
mTOR_inhibitors + CyclinD_inhibitors,0,0,0,2,2,0,2,0.0,100.0,0.0,0.0,0.0
mTOR_inhibitors + BCL2L1_inhibitors,0,1,0,1,2,1,1,50.0,50.0,50.0,0.0,0.0